# Generated by Django 5.2.5 on 2025-10-07 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_loantransactionid_loan_transaction_id'),
        ('payment', '0002_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactionid', to='loan.loantransactionid'),
        ),
    ]
