# Generated by Django 5.2.5 on 2025-09-20 00:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrower', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, help_text='An automatic generated identification number(s) for a transaction', null=True, unique=True)),
                ('loan_type', models.CharField(choices=[('personal loan', 'PERSONAL LOAN'), ('mortgage', 'MORTGAGE (HOME LOAN)'), ('auto loan', 'AUTO LOAN'), ('student loan', 'STUDENT LOAN'), ('business loan', 'BUSINESS LOAN'), ('payday loan', 'PAYDAY LOAN'), ('credit card loan', 'CREDIT CARD LOAN'), ('debt consolidation loan', 'DEBT CONSOLIDATION LOAN'), ('microfinance loan', 'MICROFINANCE LOAN'), ('agricultural loan', 'AGRICULTURAL LOAN'), ('bridge loan', 'BRIDGE LOAN'), ('equipment financing', 'EQUIPMENT FINANCING'), ('line of credit', 'LINE OF CREDIT'), ('secured loan', 'SECURED LOAN'), ('unsecured loan', 'UNSECURED LOAN')], max_length=50)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_tenure', models.CharField(choices=[('one month', 'ONE MONTH'), ('two months', 'TWO MONTH'), ('three months', 'THREE MONTH'), ('four months', 'FOUR MONTH'), ('five months', 'FIVE MONTH'), ('six months', 'SIX MONTH'), ('seven months', 'SEVEN MONTH'), ('eight months', 'EIGHT MONTH'), ('nine months', 'NINE MONTH'), ('two years', 'TWO YEARS'), ('five years', 'FIVE YEARS'), ('ten years', 'TEN YEARS')], default='one month')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Ongoing', 'ONGOING'), ('Approved', 'APPROVED'), ('Rejected', 'REJECTED'), ('Completed', 'COMPLETED'), ('Defaulted', 'DEFAULTED')], default='Ongoing', max_length=50)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loanticket_details', to='borrower.borrower')),
            ],
            options={
                'verbose_name': 'Loan Ticket',
                'verbose_name_plural': 'Loan Tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
