# Generated by Django 5.2.5 on 2025-09-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Default interest rate (%) applied to new loans', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loan Setting',
                'verbose_name_plural': 'Loan Settings',
            },
        ),
        migrations.AlterField(
            model_name='loanticket',
            name='loan_tenure',
            field=models.CharField(choices=[('one month', 'ONE MONTH'), ('two months', 'TWO MONTHS'), ('three months', 'THREE MONTHS'), ('four months', 'FOUR MONTHS'), ('five months', 'FIVE MONTHS'), ('six months', 'SIX MONTHS'), ('seven months', 'SEVEN MONTHS'), ('eight months', 'EIGHT MONTHS'), ('nine months', 'NINE MONTHS'), ('two years', 'TWO YEARS'), ('five years', 'FIVE YEARS'), ('ten years', 'TEN YEARS')], default='one month'),
        ),
    ]
