# Generated by Django 5.2.5 on 2025-09-22 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_ticket', '0002_loansettings_alter_loanticket_loan_tenure'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanTenure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenure', models.IntegerField(default=1)),
                ('text', models.CharField(default='ONE MONTH')),
            ],
        ),
        migrations.AlterField(
            model_name='loanticket',
            name='loan_type',
            field=models.CharField(choices=[('personal loan', 'PERSONAL LOAN'), ('mortgage', 'MORTGAGE (HOME LOAN)'), ('auto loan', 'AUTO LOAN'), ('student loan', 'STUDENT LOAN'), ('business loan', 'BUSINESS LOAN'), ('payday loan', 'PAYDAY LOAN'), ('credit card loan', 'CREDIT CARD LOAN'), ('debt consolidation loan', 'DEBT CONSOLIDATION LOAN'), ('microfinance loan', 'MICROFINANCE LOAN'), ('agricultural loan', 'AGRICULTURAL LOAN'), ('bridge loan', 'BRIDGE LOAN'), ('equipment financing', 'EQUIPMENT FINANCING'), ('line of credit', 'LINE OF CREDIT'), ('secured loan', 'SECURED LOAN'), ('unsecured loan', 'UNSECURED LOAN')], default='personal loan', max_length=50),
        ),
        migrations.AlterField(
            model_name='loanticket',
            name='loan_tenure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loantenure_details', to='loan_ticket.loantenure'),
        ),
    ]
