# Generated by Django 5.2.5 on 2025-10-05 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_loantransactionid_loan_transaction_id'),
        ('loan_ticket', '0003_loantenure_alter_loanticket_loan_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanticket',
            name='loan_tenure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_tenure_details', to='loan_ticket.loantenure'),
        ),
        migrations.AlterField(
            model_name='loanticket',
            name='transaction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loanticket_transactionid', to='loan.loantransactionid'),
        ),
    ]
