# Generated by Django 5.2.5 on 2025-10-07 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_loantransactionid_loan_transaction_id'),
        ('loan_ticket', '0004_alter_loanticket_loan_tenure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanticket',
            name='loan_tenure',
            field=models.PositiveIntegerField(help_text='Enter loan tenure in months'),
        ),
        migrations.AlterField(
            model_name='loanticket',
            name='transaction_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loanticket_transactionid', to='loan.loantransactionid'),
        ),
        migrations.DeleteModel(
            name='LoanTenure',
        ),
    ]
