# Generated by Django 5.2.5 on 2025-10-09 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_transactionid_alter_loan_transaction_id'),
        ('loan_ticket', '0005_alter_loanticket_loan_tenure_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loansettings',
            options={'get_latest_by': 'updated_at', 'verbose_name': 'Loan Setting', 'verbose_name_plural': 'Loan Settings'},
        ),
        migrations.AlterField(
            model_name='loanticket',
            name='transaction_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loanticket_trans_id', to='loan.transactionid'),
        ),
    ]
