# Generated by Django 5.2.5 on 2025-09-02 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0002_borrower_user_profile'),
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_folder',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_name',
        ),
        migrations.AddField(
            model_name='document',
            name='borrower',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='document_details', to='borrower.borrower'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_category',
            field=models.CharField(choices=[('identity', 'Proof of Identity'), ('address', 'Proof of Address')], default='identity', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('NIN', 'National ID Card / NIN Slip'), ('BVN', 'BVN Confirmation Document'), ('PASSPORT', 'International Passport'), ('PHOTO', 'Passport Photograph'), ('DL', "Driver's License"), ('PVC', "Permanent Voter's Card"), ('UTILITY', 'Utility Bill')], default='NIN', max_length=150),
        ),
    ]
