# Generated by Django 5.2.5 on 2025-09-11 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrower', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_category', models.CharField(choices=[('identity', 'Proof of Identity'), ('address', 'Proof of Address')], default='identity', max_length=50)),
                ('document_type', models.CharField(choices=[('NIN', 'National ID Card / NIN Slip'), ('BVN', 'BVN Confirmation Document'), ('PASSPORT', 'International Passport'), ('PHOTO', 'Passport Photograph'), ('DL', "Driver's License"), ('PVC', "Permanent Voter's Card"), ('UTILITY', 'Utility Bill')], default='NIN', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('borrower', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='document_details', to='borrower.borrower')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
