# Generated by Django 5.2.5 on 2025-09-20 00:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrower', '0001_initial'),
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('bvn_number', models.CharField(blank=True, help_text='Bank Verification Number', max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 11-digit BVN.', regex='^\\d{11}$')])),
                ('tin_number', models.CharField(blank=True, help_text='TAX Identification Number', max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid TIN (8-4 format or 12 digits).', regex='^(?:\\d{8}-\\d{4}|\\d{12})$')])),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kyc_details', to='borrower.borrower')),
                ('documents', models.ManyToManyField(blank=True, related_name='kyc_associations', to='document.document')),
            ],
            options={
                'verbose_name': 'KYC',
                'verbose_name_plural': 'KYC Details',
                'ordering': ['-created_at'],
            },
        ),
    ]
