# Generated by Django 5.2.5 on 2025-09-22 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='documents',
        ),
        migrations.AddField(
            model_name='kyc',
            name='documents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kyc_associations', to='document.document'),
        ),
    ]
