# Generated by Django 5.2.5 on 2025-09-22 16:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
        ('kyc', '0002_remove_kyc_documents_kyc_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='bvn_number',
            field=models.CharField(help_text='Bank Verification Number', max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 11-digit BVN.', regex='^\\d{11}$')]),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='documents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kyc_associations', to='document.document'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='tin_number',
            field=models.CharField(help_text='TAX Identification Number', max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid TIN (8-4 format or 12 digits).', regex='^(?:\\d{8}-\\d{4}|\\d{12})$')]),
        ),
    ]
