# Generated by Django 5.2.5 on 2025-10-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_alter_kyc_bvn_number_alter_kyc_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='completion_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
