# Generated by Django 5.2.5 on 2025-09-20 00:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrower', '0001_initial'),
        ('loan_ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, help_text='An automatic generated identification number(s) for a transaction', unique=True)),
                ('emi_no', models.IntegerField()),
                ('emi_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Overdue', 'Overdue'), ('Waived', 'Waived')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emi_details', to='borrower.borrower')),
                ('loan_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emis', to='loan_ticket.loanticket')),
            ],
            options={
                'verbose_name': 'EMI',
                'verbose_name_plural': 'EMIs',
                'ordering': ['loan_ticket', 'emi_no'],
            },
        ),
    ]
