# Generated by Django 5.2.5 on 2025-09-20 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emi', '0001_initial'),
        ('payment', '0001_initial'),
        ('penalty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emi',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emi_settled_by_payment', to='payment.payment'),
        ),
        migrations.AddField(
            model_name='emi',
            name='penalty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emi_penalized', to='penalty.penalty'),
        ),
        migrations.AlterUniqueTogether(
            name='emi',
            unique_together={('loan_ticket', 'emi_no')},
        ),
    ]
