# Generated by Django 5.2.5 on 2025-10-09 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emi', '0004_alter_emi_transaction_id'),
        ('loan', '0003_transactionid_alter_loan_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emi',
            name='transaction_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emi_trans_id', to='loan.transactionid'),
        ),
    ]
