# Generated by Django 5.2.4 on 2025-07-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='document_folder',
            field=models.CharField(max_length=150, verbose_name='Document Folder'),
        ),
    ]
