# Generated by Django 5.2.4 on 2025-07-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_management', '0002_alter_documents_document_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='completion_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
