# Generated by Django 5.2.5 on 2025-08-22 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emi', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Waived', 'Waived')], default='Pending', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='emi.emi')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties_paid', to='payment.payment')),
            ],
            options={
                'verbose_name': 'Penalty',
                'verbose_name_plural': 'Penalties',
                'ordering': ['-created_at'],
            },
        ),
    ]
