# Generated by Django 5.2.5 on 2025-08-28 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0002_borrower_user_profile'),
        ('penalty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalty',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='borrower.borrower'),
        ),
    ]
