# Generated by Django 5.2.5 on 2025-09-11 13:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrower', '0001_initial'),
        ('document', '0001_initial'),
        ('emi', '0001_initial'),
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tenure_months', models.IntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISBURSED', 'Disbursed'), ('CLOSED', 'Closed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='borrower.borrower')),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.document')),
                ('emi', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emi.emi')),
                ('kyc', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kyc.kyc')),
            ],
        ),
    ]
