# Generated by Django 5.2.5 on 2025-10-09 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emi', '0005_alter_emi_transaction_id'),
        ('loan', '0003_transactionid_alter_loan_transaction_id'),
        ('loan_ticket', '0006_alter_loansettings_options_and_more'),
        ('payment', '0004_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoanTransactionID',
        ),
    ]
