# Generated by Django 5.2.5 on 2025-09-01 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0002_borrower_user_profile'),
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kyc_details', to='borrower.borrower'),
        ),
    ]
