# Generated by Django 5.2.5 on 2025-10-09 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_transactionid_alter_loan_transaction_id'),
        ('penalty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalty',
            name='transaction_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penalty_trans_id', to='loan.transactionid'),
        ),
    ]
